[package]
name = "hcbs-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
ctrlc = "3.5.1"
env_logger = "0.11.8"
fuser = "0.16.0"
libc = "0.2.180"
log = "0.4.29"
sysinfo = "0.38.0"
